POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOjMsImlhdCI6MTcxMDMyNzc4OH0.IqndwT8WES1ekAP1vzpGM-v8saaGoIUpBqS4FCGPjfk



{
  "content": "another note",
  "important": true
}