POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imx5bngiLCJpZCI6MSwiaWF0IjoxNzEwNDk1Mjg4fQ.1cHQCtZ4wW2_pNNPcDDu5LUEs7bbiqhwQv-wdkyty4w



{
  "content": "lynx first note",
  "important": true
}